//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGuiTietKiem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSTK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSTK()
        {
            this.SoTietKiems = new HashSet<SoTietKiem>();
        }
    
        public int MaLoaiSo { get; set; }
        public string TenLoaiSo { get; set; }
        public double LaiSuat { get; set; }
        public int SoThang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoTietKiem> SoTietKiems { get; set; }
    }
}
