//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGuiTietKiem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoTietKiem
    {
        public int MaSTK { get; set; }
        public int MaNV { get; set; }
        public int MaKH { get; set; }
        public int MaLoaiSo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<decimal> SoTienGui { get; set; }
        public Nullable<System.DateTime> NgayRut { get; set; }
        public Nullable<decimal> SoTienRut { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiSTK LoaiSTK { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
